version: '3.7'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql_host
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: g14_farma
      MYSQL_DATABASE: cac_20150_g14_farma_db
    ports:
      - 3306:3306

  frontend:
    image: httpd:latest
    container_name: frontend
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/

  backend:
    build: ./backend
    container_name: backend
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    restart: on-failure