# Generated by Django 5.0.6 on 2024-07-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0002_alter_producto_image_alter_producto_name'),
        ('app_productos', '0006_alter_producto_description'),
    ]

    operations = [
    ]
